import os
import xml.etree.ElementTree as ET
import matplotlib.pyplot as plt
import numpy as np

def parse_tb2j_multibinit_xml(xml_path):
    """
    Parses the System_definition (Multibinit) XML file generated by TB2J.
    Calculates distances using the unit cell and atomic positions.
    """
    if not os.path.exists(xml_path):
        print(f"Error: {xml_path} not found.")
        return None

    tree = ET.parse(xml_path)
    root = tree.getroot()

    # Constants
    BOHR_TO_ANGSTROM = 0.52917721
    EV_TO_MEV = 1000.0

    # 1. Parse Unit Cell (9 floats)
    cell_elem = root.find("unit_cell")
    cell_flat = [float(x) for x in cell_elem.text.split()]
    cell_matrix = np.array(cell_flat).reshape(3, 3) * BOHR_TO_ANGSTROM

    # 2. Parse Atomic Positions
    atoms_pos = {}
    for atom in root.findall("atom"):
        idx = int(atom.get("index_spin"))
        if idx == 0: continue # Skip non-magnetic atoms
        pos_text = atom.find("position").text.split()
        pos = np.array([float(x) for x in pos_text]) * BOHR_TO_ANGSTROM
        atoms_pos[idx] = pos

    data = []
    # 3. Parse Exchange Terms
    exchange_list = root.find("spin_exchange_list")
    if exchange_list is None:
        print("No spin_exchange_list found in XML.")
        return None

    for term in exchange_list.findall("spin_exchange_term"):
        # ijR format: i j R1 R2 R3
        ijR_text = term.find("ijR").text.split()
        i, j = int(ijR_text[0]), int(ijR_text[1])
        R_vec = np.array([int(x) for x in ijR_text[2:]])

        # Data: J_isotropic [other components]
        # We take the first value as the isotropic exchange J
        data_text = term.find("data").text.split()
        try:
            j_val_ev = float(data_text[0])
            if np.isnan(j_val_ev): continue
        except ValueError:
            continue
            
        j_val_mev = j_val_ev * EV_TO_MEV

        # 4. Calculate Distance: |(pos_j + R*cell) - pos_i|
        pos_i = atoms_pos[i]
        pos_j = atoms_pos[j]
        # Shift j by lattice vector R
        pos_j_shifted = pos_j + R_vec @ cell_matrix
        dist = np.linalg.norm(pos_j_shifted - pos_i)

        # Avoid self-interaction at distance 0 (J_ii at R=0)
        if dist < 0.01: continue

        data.append({
            'dist': dist,
            'j': j_val_mev,
            'pair': f"{i}-{j}"
        })

    return data

def plot_j_vs_distance(xml_path, save_path="exchange_plot.png"):
    """
    Creates a plot of J (meV) vs Distance (A) from a TB2J Multibinit XML file.
    """
    print(f"Parsing {xml_path}...")
    data = parse_tb2j_multibinit_xml(xml_path)
    
    if not data or len(data) == 0:
        print("No valid J values found (ensure your calculation didn't return 'nan').")
        return

    distances = np.array([d['dist'] for d in data])
    j_values = np.array([d['j'] for d in data])

    plt.figure(figsize=(9, 6))
    plt.axhline(0, color='black', lw=1, ls='--', alpha=0.5) # Zero line
    
    # Scatter plot of J values
    plt.scatter(distances, j_values, color='#3498db', edgecolors='white', 
                s=80, alpha=0.8, label='$J_{ij}$ (Exchange)')

    plt.xlabel('Distance $R_{ij}$ (Å)', fontsize=12)
    plt.ylabel('Exchange $J$ (meV)', fontsize=12)
    plt.title(f'Exchange Interaction vs. Distance\n{os.path.basename(xml_path)}', fontsize=14)
    plt.grid(True, linestyle=':', alpha=0.4)
    
    # Identify and label unique neighbors (J1, J2, J3...)
    # We round distances slightly to group equivalent bonds
    unique_dists, indices = np.unique(np.round(distances, 3), return_index=True)
    sorted_idx = np.argsort(unique_dists)
    
    for count, idx in enumerate(sorted_idx[:3]): # Label first 3 neighbors
        d = distances[indices[idx]]
        j = j_values[indices[idx]]
        plt.annotate(f'$J_{count+1}$', xy=(d, j), xytext=(0, 10), 
                     textcoords='offset points', ha='center', fontweight='bold')

    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    print(f"Plot saved successfully to: {save_path}")
    plt.show()

if __name__ == "__main__":
    # Path to your exchange.xml (Multibinit format)
    target_xml = "./Datasets/CrI3-Relax/FM/_strain_uniaxial_x_-0.0100/tmp/TB2J_results/Multibinit/exchange.xml"
    
    if os.path.exists(target_xml):
        plot_j_vs_distance(target_xml)
    else:
        print(f"File {target_xml} not found in current directory.")